spring:
  application:
    name: member-tracking-api # 서비스 이름 설정 (서비스 등록/로깅 등에서 사용됨) (Actuator 등에서 사용됨)
  profiles:
    active: dev # 현재 활성화 할 profile 설정 (예: local, dev, prod) (application-dev.yaml 파일을 자동 인식함)
    include:
      - mongo # mongodb

server:
  port: 8082